package com.example.getwell.screens.relaxScreen.gamesection.dailyref

object ReflectionQuestions {
    val dailyQuestions = listOf(
        "What made you smile today?",
        "What is something you are grateful for today?",
        "How did you handle a challenging situation today?",
        "What are three things you appreciate about yourself?",
        "Who or what inspired you today?",
        "What did you learn today?",
        "What was the highlight of your day?",
        "How did you take care of yourself today?",
        "What is one thing you could improve about today?",
        "What are you looking forward to tomorrow?",
        "Did you face any fears today?",
        "What is something you are proud of?",
        "What made you feel calm today?",
        "What relationships are you most thankful for?",
        "What was your most significant accomplishment today?",
        "What did you do to help someone today?",
        "What is something you need to let go of?",
        "How do you feel about the progress you’ve made this week?",
        "What is one thing you wish you had done differently today?",
        "What new habit would you like to develop?",
        "What was the most peaceful moment of your day?",
        "Who made you feel loved or appreciated today?",
        "What did you do to make yourself happy today?",
        "What are your goals for tomorrow?",
        "How did you feel about your productivity today?",
        "What does your ideal day look like?",
        "What can you do tomorrow to make it a better day?",
        "What is something you feel anxious about?",
        "What has been on your mind recently?",
        "What motivates you to keep going on hard days?",
        "What made you feel alive today?",
        "How would you describe today in three words?",
        "Did you encounter any negative thoughts today? How did you handle them?",
        "What is something you’re working towards?",
        "How can you show kindness to others tomorrow?",
        "What are some things that always improve your mood?",
        "What was your most recent big achievement?",
        "What self-care habits help you relax?",
        "What is your biggest strength?",
        "What do you wish more people knew about you?",
        "How have you changed in the past year?",
        "What’s a memory that makes you smile?",
        "Who or what are you thankful for today?",
        "What was the hardest part of your day?",
        "What is something you would like to do more of?",
        "What does success mean to you?",
        "What are three things you love about your life?",
        "What does self-care mean to you?",
        "What is one thing you want to work on this week?",
        "What goals are you currently working on?",
        "What made you feel loved today?",
        "How do you manage stress?",
        "What are some things that make you feel balanced?",
        "What do you need more of in your life?",
        "What are you most proud of this month?",
        "What was a recent challenge you overcame?",
        "What is something you’ve learned about yourself?",
        "What is something you wish to forgive yourself for?",
        "How have your priorities changed recently?",
        "What are some things you want to explore?",
        "What qualities do you admire in others?",
        "What are your favorite hobbies or activities?",
        "What is something you want to remember from today?",
        "What or who makes you feel safe?",
        "What energizes you?",
        "What are you passionate about?",
        "What’s something you did today that you’re proud of?",
        "What’s a lesson you learned from a mistake?",
        "How do you define happiness?",
        "What are your personal values?",
        "What have you done recently to step out of your comfort zone?",
        "What is something you need to be more mindful of?",
        "How do you want to grow in the next month?",
        "What does being fulfilled mean to you?",
        "What motivates you to work hard?",
        "What is a kind thing someone did for you recently?",
        "How can you be kinder to yourself?",
        "What’s something you would like to change about your day?",
        "What’s one thing you want to let go of?",
        "What does relaxation mean to you?",
        "What made you feel proud recently?",
        "Who do you admire and why?",
        "What do you love most about yourself?",
        "How do you handle criticism?",
        "What does inner peace mean to you?",
        "What is something that made you feel accomplished?",
        "What is a goal you achieved recently?",
        "What would you say is your greatest strength?",
        "What brings you a sense of purpose?",
        "What was the most challenging part of your day?",
        "What is a habit you want to work on?",
        "What do you need to feel more balanced?",
        "How do you recharge after a long day?",
        "What would you say has been your greatest achievement so far?",
        "What is one thing you are hopeful about?",
        "What’s one thing you’ve been putting off?",
        "What was a positive moment today?",
        "How do you express gratitude?",
        "What is your biggest dream?",
        "What is something you’d like to learn or improve?",
        "What do you believe is the most important thing in life?"
    )

    fun getRandomQuestion(): String = dailyQuestions.random()
}